# Generated by Django 3.2.9 on 2021-12-05 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='profile_images')),
                ('days_logged_id', models.IntegerField(default=0)),
                ('favorite_genre', models.CharField(max_length=15)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={}, verbose_name={'center': [23.78080079103708, 90.4077459260738], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'language': 'auto', 'marker_color': 'red', 'message_404': 'undefined address', 'navigation_buttons': True, 'placeholder': 'Pick a location on map below', 'readonly': True, 'rotate': False, 'style': 'mapbox://styles/mapbox/outdoors-v11', 'track_location_button': True, 'zoom': 13})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
