# Generated by Django 3.2.9 on 2021-12-05 21:32

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [23.78080079103708, 90.4077459260738], 'zoom': 13}),
        ),
    ]
