# Generated by Django 3.2.9 on 2021-12-10 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211210_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', height_field=300, max_length=1000, upload_to='profile_images', width_field=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=mapbox_location_field.models.LocationField(default=[23.78091, 90.40756], map_attrs={}),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reciever', to='users.profile')),
                ('review_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sender', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_receiver', to='users.profile')),
                ('report_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sender', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(max_length=400, upload_to='chat_uploads/%Y/%m/%d/%h/%m/%s/')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_messages',
            field=models.ManyToManyField(related_name='_users_profile_user_messages_+', through='users.Messages', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_reports',
            field=models.ManyToManyField(related_name='_users_profile_user_reports_+', through='users.Reports', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_reviews',
            field=models.ManyToManyField(related_name='_users_profile_user_reviews_+', through='users.Reviews', to='users.Profile'),
        ),
    ]
