# Generated by Django 3.2.9 on 2021-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_favorite_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Action & Adventure', 'Action & Adventure'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Biography', 'Biography'), ('Science & Technology', 'Science & Technology')], max_length=20),
        ),
    ]
