# Generated by Django 3.2.9 on 2021-12-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
