# Generated by Django 3.2.9 on 2021-12-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='chat_uploads'),
        ),
    ]
