# Generated by Django 3.2.9 on 2021-12-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_messages_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
