# Generated by Django 3.2.9 on 2021-12-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211212_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='days_logged_id',
            new_name='days_logged_in',
        ),
    ]
