# Generated by Django 3.2.9 on 2021-12-10 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('genres', models.CharField(choices=[('Fantasy', 'FANTASY'), ('Sci-Fi', 'SCIENCE FICTION'), ('Action & Adventure', 'ACTION & ADVENTURE'), ('Mystery', 'MYSTERY'), ('Horror', 'HORROR'), ('Thriller', 'THRILLER'), ('Romance', 'ROMANCE'), ('Biography', 'BIOGRAPHY'), ('Science & Technology', 'SCIENCE & TECH'), ('Humor', 'HUMOR'), ('History', 'HISTORY'), ('Children', 'CHILDREN'), ('Travel', 'TRAVEL')], max_length=40)),
                ('pages', models.IntegerField(blank=True)),
                ('edition', models.IntegerField(blank=True)),
                ('author', models.ManyToManyField(to='trades.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('condition', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Fair'), (3, 'Acceptable'), (4, 'Well Worn'), (5, 'Poor')])),
                ('negotiable', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('listing_type', models.BooleanField(choices=[(True, 'Sell'), (False, 'Exchange')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_book', to='trades.book')),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('options', models.ManyToManyField(related_name='suggested_books', to='trades.Book')),
            ],
        ),
    ]
