# Generated by Django 3.2.9 on 2021-12-10 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='default.png', height_field=210, upload_to='book_covers', width_field=90),
        ),
        migrations.AddField(
            model_name='listing',
            name='descriptions',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='viewed_by',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='wishlisted_by',
            field=models.ManyToManyField(related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.IntegerField(choices=[('Excellent', 1), ('Fair', 2), ('Acceptable', 3), ('Well Worn', 4), ('Poor', 5)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.BooleanField(choices=[('Sell', True), ('Exchange', False)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)]),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.listing')),
                ('tradee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', height_field=210, max_length=1000, upload_to='listing_images', width_field=90)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=200)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='trades',
            field=models.ManyToManyField(related_name='trades', through='trades.Trade', to=settings.AUTH_USER_MODEL),
        ),
    ]
