# Generated by Django 3.2.9 on 2021-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20211210_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='book_covers'),
        ),
        migrations.AlterField(
            model_name='listing_images',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='listing_images'),
        ),
    ]
