# Generated by Django 3.2.9 on 2021-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.IntegerField(choices=[(1, 'Fantasy'), (2, 'Sci-Fi'), (3, 'Action & Adventure'), (4, 'Mystery'), (5, 'Horror'), (6, 'Thriller'), (7, 'Romance'), (8, 'Biography'), (9, 'Science & Technology'), (10, 'Humor'), (11, 'History'), (12, 'Children'), (13, 'Travel')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.BooleanField(choices=[(True, 'Sell'), (False, 'Exchange')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
