# Generated by Django 3.2.9 on 2021-12-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0007_auto_20211210_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='options',
        ),
        migrations.AddField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='trades',
            field=models.ManyToManyField(blank=True, related_name='trades', through='trades.Trade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='wishlisted_by',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing_comments',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing_comments',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trades.listing'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='trades.listing'),
        ),
    ]
