# Generated by Django 3.2.9 on 2021-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_auto_20211211_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.IntegerField(choices=[(1, 'Fantasy'), (3, 'Action & Adventure'), (4, 'Mystery'), (5, 'Horror'), (6, 'Thriller'), (7, 'Romance'), (8, 'Biography'), (9, 'Science & Technology'), (10, 'Humor'), (11, 'History'), (12, 'Children'), (13, 'Travel')]),
        ),
    ]
