# Generated by Django 3.2.9 on 2021-12-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_alter_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Action & Adventure', 'Action & Adventure'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Biography', 'Biography'), ('Science & Technology', 'Science & Technology'), ('Humor', 'Humor'), ('History', 'History'), ('Children', 'Children'), ('Travel', 'Travel')], max_length=25),
        ),
    ]
