# Generated by Django 3.2.9 on 2021-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_auto_20211212_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='book_covers'),
        ),
    ]
