# Generated by Django 3.2.9 on 2021-12-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Is Having A Sale', 'Is Having A Sale'), ('Is Performing A Giveaway', 'Is Performing A Giveaway'), ('Shared A Post!', 'Shared A Post!'), ('Has Shared A Book Review!', 'Has Shared A Book Review!'), ('Is Reading A New Book!', 'Is Reading A New Book!')], default='Post Share', max_length=30),
        ),
    ]
