# Generated by Django 3.2.9 on 2021-12-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20211228_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
